server:
  port: 8085

spring:
  application:
    name: raceflow-metrics-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/metrics
    username: ${DB_USER:raceflow}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}


management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: local
